#!/bin/sh
echo 'Creating symbolic links for primariy CSS file'
ln -s ../css_file.css chrome/css_file.css
ln -s ../../css_file.css safari/AAU\ Moodle\ Optimizer.safariextension/css_file.css
ln -s ../css_file.css firefox/data/css_file.css
